apply plugin: 'com.android.library'

android {
	namespace "com.jiangdg.libuvc"
	compileSdk 34
	ndkVersion "26.1.10909125"

	defaultConfig {
		minSdk 24
		targetSdk 34
	}

	buildTypes {
		release {
			minifyEnabled false
		}
	}

	compileOptions {
		sourceCompatibility JavaVersion.VERSION_1_8
		targetCompatibility JavaVersion.VERSION_1_8
	}

}

dependencies {
	implementation "androidx.appcompat:appcompat:1.6.1"
	implementation 'com.elvishew:xlog:1.11.0'
}
